version: '3.8'
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
    ports:
      - 5173:80