CREATE TABLE public."user"
(
	"id"        integer primary key generated by default as identity,
	company_id  uuid      NULL,
	username    TEXT      NOT NULL UNIQUE,
	pass_hash   bytea     NOT NULL,
	isAdmin     boolean default FALSE,
	created_at  timestamp NOT NULL,
	modified_at timestamp NULL,
	deleted_at  timestamp NULL
);
COMMENT ON TABLE "user" IS 'Пользователи';

